name: Build and deploy the application to Koyeb

on:
  schedule:
    - cron: '25 8 * * *'
  push:
    branches:
      - '*'

jobs:
  deploy:
    concurrency:
      group: "${{ github.ref_name }}"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: "${{ secrets.KOYEB_EXAMPLES_APPS_TOKEN }}"

      - name: Create application secret
        uses: koyeb/action-git-deploy/secret@v1
        with:
          secret-name: MERN_MONGO_URL
          secret-value: "${{ secrets.MONGO_URL }}"

      - name: Build and deploy the application
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: mern-${{ github.ref_name }}
          service-env: "CONNECTION_STRING=@MERN_MONGO_URL"
          service-ports: "3000:http"
          service-routes: "/:3000"
          git-build-command: yarn build-client
          git-run-command: yarn start
          skip-cache: true
